# Generated by Django 4.2.7 on 2023-12-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_category_product_catefory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catefory',
            new_name='category',
        ),
    ]
